// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXZBs2BuJ-s-Kc-qK2uVl8umD3OwkwVnw',
    appId: '1:410919083565:web:a5c5f86f8b8ce1920462a4',
    messagingSenderId: '410919083565',
    projectId: 'ispgayaapp-143a0',
    authDomain: 'ispgayaapp-143a0.firebaseapp.com',
    storageBucket: 'ispgayaapp-143a0.firebasestorage.app',
    measurementId: 'G-CLYXFZKJRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnLdgb5Xy54BGIHqet_Ni-AStVa6F1YBQ',
    appId: '1:410919083565:android:b1524266ee8b55950462a4',
    messagingSenderId: '410919083565',
    projectId: 'ispgayaapp-143a0',
    storageBucket: 'ispgayaapp-143a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0qmZL1LuAdoXV0SUC8FPTWvn_A7xkjig',
    appId: '1:410919083565:ios:01abfd69e7b7e6da0462a4',
    messagingSenderId: '410919083565',
    projectId: 'ispgayaapp-143a0',
    storageBucket: 'ispgayaapp-143a0.firebasestorage.app',
    iosBundleId: 'com.example.applicationispgaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0qmZL1LuAdoXV0SUC8FPTWvn_A7xkjig',
    appId: '1:410919083565:ios:01abfd69e7b7e6da0462a4',
    messagingSenderId: '410919083565',
    projectId: 'ispgayaapp-143a0',
    storageBucket: 'ispgayaapp-143a0.firebasestorage.app',
    iosBundleId: 'com.example.applicationispgaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXZBs2BuJ-s-Kc-qK2uVl8umD3OwkwVnw',
    appId: '1:410919083565:web:bb77e87faeb4acf60462a4',
    messagingSenderId: '410919083565',
    projectId: 'ispgayaapp-143a0',
    authDomain: 'ispgayaapp-143a0.firebaseapp.com',
    storageBucket: 'ispgayaapp-143a0.firebasestorage.app',
    measurementId: 'G-E3D1TG9LW9',
  );
}
